---
name: on_hello_event1
pack: hello_stackstorm
description: Sample rule firing on hello_st2.event1.
enabled: true
trigger:
    type: hello_st2.event1
action:
    ref: hello_st2.hello
    parameters:
        greeting: Hello

